### PR TITLE
Use pnpm and monorepo

### LINKED ISSUE #49: Make it a monorepo
... with pnpm, and migrate extensions into this repo.

This is from a conversation with @strogonoff .  Idea is that Paneron and the extensions have tight version dependencies, so having them in a monorepo would make testing, etc. more maintainable.

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
Fixes #49

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ribose-jeffreylau will this come with CI builds of Paneron? Right now we are still listing Beta24 when locally we have Beta25. Thanks!

**Comment by ribose-jeffreylau** [comment]
@ronaldtse Yes, this PR (or the next) will have a working CI release workflow.

**Comment by ribose-jeffreylau** [comment]
Currently, tests on Windows are broken due to reasons detailed here:

- https://github.com/electron-userland/electron-builder/issues/6933

However, a work-around exists and will be tested: https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1222425507

**Comment by strogonoff** [comment]
Thanks @ribose-jeffreylau!

By the way, my earlier plan was to use a new repository for the monorepo (e.g., https://github.com/paneron/monorepo), to prevent any issues and keep the app workable throughout the move, and then archive/redirect this repository. Do you think that’s unnecessary?

**Comment by strogonoff** [comment]
Other than that it looks alright and I want to give it a spin…

**Comment by ribose-jeffreylau** [comment]
@strogonoff Sorry, I think you mentioned about the separate repo but I totally forgot about it...

I was thinking we could just maintain separate branches (release branches for tagged and published releases) so all versions could coexist in the same repo.  That and it helps consolidate all truths about the code, regardless of source code file structure.

But the monorepo rework here is nearly done, just need to figure out what causes the 'electron-builder' step to freeze in CI.

**Comment by ribose-jeffreylau** [comment]
[Now ubuntu's `release` workflow passes](https://github.com/paneron/paneron/actions/runs/3539134786), and while the other two (windows and macos) fail, [they also fail in the master branch](https://github.com/paneron/paneron/actions/runs/3539205768) due to apparently the same reasons (private keys / certs expired) as this feature branch.  So I guess we can safely ignore those for now, and open tickets for those separately.

**Review by ronaldtse — APPROVED** [review]
Thank you @ribose-jeffreylau !

**Comment by ribose-jeffreylau** [comment]
Notarizing works.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau can we merge this first and then fix the Windows code signing?

**Comment by strogonoff** [comment]
I checked a diff between `dependencies` and `devDependencies`, and it seems there were not many changes.

- electron-build changed version 22 &rarr; 23
- some new dependencies were added—I assume they were undeclared but used anyway (because they were depended upon by a dependency)

There were no changes between `resolutions` versions.

```diff
diff --git b/before.txt a/after.txt
index 7161bb5..fe7a30e 100644
--- b/before.txt
+++ a/after.txt
@@ -11,8 +11,8 @@
      "@react-three/fiber": "^7.0.19",
      "@riboseinc/isogit-lfs": "0.1.6",
      "@riboseinc/paneron-extension-glossarist": "^1.0.0-dev34",
-     "@riboseinc/paneron-registry-kit": "2.0.0-alpha5",
      "@riboseinc/paneron-extension-kit": "2.0.0-alpha24",
+     "@riboseinc/paneron-registry-kit": "2.0.0-alpha5",
      "@riboseinc/reprose": "1.0.0-alpha11",
      "@types/mark.js": "^8.11.5",
      "asciidoctor": "^2.2.5",
@@ -54,6 +54,7 @@
      "react-window": "^1.8.5",
      "retry-axios": "^2.4.0",
      "rough-notation": "^0.5.1",
+     "run-script-os": "^1.1.6",
      "semver": "^7.3.2",
      "source-map-support": "^0.5.19",
      "subleveldown": "^5.0.1",
@@ -63,6 +64,7 @@
    },
    "devDependencies": {
      "@emotion/eslint-plugin": "^11.0.0",
+     "@types/abstract-leveldown": "^7.2.0",
      "@types/async-lock": "^1.1.1",
      "@types/chai": "^4.2.18",
      "@types/chai-as-promised": "^7.1.4",
@@ -73,6 +75,7 @@
      "@types/fs-extra": "^9.0.1",
      "@types/globby": "^9.1.0",
      "@types/js-yaml": "^4.0.1",
+     "@types/level-codec": "^9.0.1",
      "@types/leveldown": "^4.0.2",
      "@types/levelup": "^4.3.0",
      "@types/lexicographic-integer": "^1.1.0",
@@ -90,30 +93,37 @@
      "@types/throttle-debounce": "^2.1.0",
      "@typescript-eslint/eslint-plugin": "^5.3.1",
      "@typescript-eslint/parser": "^5.3.1",
+     "app-builder-bin": "3.7.1",
+     "app-builder-lib": "23.6.0",
      "chai": "^4.3.4",
      "chai-as-promised": "^7.1.1",
      "commitizen": "^4.1.2",
      "cross-env": "^7.0.0",
+     "css-loader": "5.2.7",
      "cz-conventional-changelog": "3.3.0",
      "electron": "12.2.2",
-     "electron-builder": "^22.11.7",
+     "electron-builder": "23.6.0",
      "electron-builder-notarize": "^1.1.2",
      "electron-react-devtools": "^0.5.3",
      "electron-webpack": "^2.8.2",
      "electron-webpack-ts": "^4.0.1",
      "eslint": "^7.13.0",
      "esm": "^3.2.25",
+     "html-loader": "1.3.2",
      "husky": "^4.2.5",
      "keytar": "^6.0.1",
      "mocha": "^8.4.0",
      "native-ext-loader": "^2.3.0",
      "npm-run-all": "^4.1.5",
+     "observable-fns": "^0.6.1",
      "prettier": "^2.0.5",
      "spectron": "^15.0.0",
+     "style-loader": "2.0.0",
      "stylelint": "^13.7.2",
      "stylelint-config-standard": "^20.0.0",
      "threads": "^1.6.3",
      "threads-plugin": "^1.4.0",
+     "ts-loader": "8.0.4",
      "ts-mocha": "^8.0.0",
      "typescript": "^4.4.2",
      "typescript-plugin-css-modules": "^2.2.0",
```

**Comment by ronaldtse** [comment]
@strogonoff can you merge this? The Windows signing issue will take some time since there is a Digicert issue that we cannot control right now. Thanks.

**Comment by ronaldtse** [comment]
Actually I'll just do it :-) Done.

**Pull request merged**
