### PR TITLE
#104 test-dist for macos

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #104

### CODE REVIEW

**Review by ribose-jeffreylau — APPROVED** [review]
LGTM

**Comment by strogonoff** [comment]
@ribose-jeffreylau @CAMOBAP can I have maybe a sentence about what this change is doing? The issue just says “Implement test-dist for macos and windows”, why do we want this?

**Comment by CAMOBAP** [comment]
> @ribose-jeffreylau @CAMOBAP can I have maybe a sentence about what this change is doing? The issue just says “Implement test-dist for macos and windows”, why do we want this?

Because recently CI produced a "bad" build for macos, so I proposed to add simple app test, not much to say)

**Comment by ribose-jeffreylau** [comment]
> Because recently CI produced a "bad" build for macos, so I proposed to add simple app test, not much to say)

@strogonoff This is what I had in mind as well.

**Comment by strogonoff** [comment]
@CAMOBAP I see. And it looks like you also made `test-dist` a requirement for `update-website`, right? Makes sense.

Let me understand it more clearly, in case `test-dist` fails

- Website will *not* be updated, right?
- Will built artifacts still be attached to draft release?

Note that generally we don’t need to update website until draft release is published, which is a manual action performed through GitHub releases GUI after app is hand-tested. But generally it doesn’t hurt to update website any time, because site build process will only look at already *published* releases anyway.

**Comment by CAMOBAP** [comment]
> Website will not be updated, right?

Yes, this job will not be started

> Will built artifacts still be attached to draft release?

Nope, it will not be attached

I just copied behavior that was in `ubuntu` workflow

**Comment by ribose-jeffreylau** [comment]
>     * Will built artifacts still be attached to draft release?

Wait, has this ever been a thing?

**Comment by strogonoff** [comment]
> 

Thanks. 

> > ```
> > * Will built artifacts still be attached to draft release?
> > ```
> 
> 
> Wait, has this ever been a thing?

@ribose-jeffreylau please see https://github.com/paneron/paneron#releasing

EDIT: I don’t know if they ever were being attached if build failed, but they are expected to be attached any time build in `release` branch succeeds. Since `build-dist` happens before `test-dist`, I wanted to make sure artifacts will not be attached after `build-dist` until `test-dist` finishes successfully.

**Comment by CAMOBAP** [comment]
@strogonoff @ribose-jeffreylau to be on the same page it will not be attached if test fail, if tests passed the artifact will be attached

**Comment by strogonoff** [comment]
@CAMOBAP since you touched update-website in this PR, perhaps you can help figure out why website isn’t updating ;) (assigned you another issuse)

**Comment by ribose-jeffreylau** [comment]
>  but they are expected to be attached any time build in `release` branch succeeds…

Has it ever worked?  If so, I never realized it...  Curious how it works if it still does / how it worked if it did.

**Comment by CAMOBAP** [comment]
Recap previous releases:
 - 2.1.4 - not updated because windows failed https://github.com/paneron/paneron/actions/runs/5782392990
 - 2.1.3 - not updated because credentials issue https://github.com/paneron/paneron/actions/runs/5656237863/job/15323450531

@strogonoff can you confirm that `secrets.GH_PANERON_CI_TOKEN` exists and up to date?

**Comment by strogonoff** [comment]
> > but they are expected to be attached any time build in `release` branch succeeds…
> 
> Has it ever worked? If so, I never realized it... Curious how it works if it still does / how it worked if it did.

@ribose-jeffreylau  It still works after your refactor. That’s how I verify that release process works after CI updates (by downloading built artifact from release page).

In fact, this is something you should verify too after you merge updated CI to release branch. We need to make sure the release process as described in README still works fully.

**Comment by strogonoff** [comment]
> @strogonoff can you confirm that `secrets.GH_PANERON_CI_TOKEN` exists and up to date?

In this repository or in `paneron.org`? I can’t but maybe @ribose-jeffreylau can check.

**Comment by strogonoff** [comment]
I’m going to merge this tomorrow, today we’ll publish v2.1.5 (first post CI refactor release).

**Comment by ribose-jeffreylau** [comment]
> It still works after your refactor.

🤯 

May I ask what its mechanism is?  I don't see it referenced in our workflow files.  Maybe I have missed something?

**Comment by ribose-jeffreylau** [comment]
> > @strogonoff can you confirm that `secrets.GH_PANERON_CI_TOKEN` exists and up to date?
> 
> In this repository or in `paneron.org`? I can’t but maybe @ribose-jeffreylau can check.

It was last updated on 11th July.

**Comment by CAMOBAP** [comment]
@ribose-jeffreylau @strogonoff I think I faced with similar issue some time before https://github.com/paneron/paneron/pull/106

**Comment by strogonoff** [comment]
> > It still works after your refactor.
> 
> 🤯
> 
> May I ask what its mechanism is? I don't see it referenced in our workflow files. Maybe I have missed 

I don’t know it well enough but maybe @CAMOBAP can see how it works. Before your refactor it was part of Electron build action we used. (I think.)

**Comment by ribose-jeffreylau** [comment]
> why website isn’t updating ;) (assigned you another issue)

@strogonoff  Manually running `update-website.yml` works right now on `release`: https://github.com/paneron/paneron/actions/runs/5877984413/job/15939164062

It wasn't updating probably because the token was expired.

The fact that it now triggers update successfully indicates that it would also work when a new release is pushed next time.

**Comment by CAMOBAP** [comment]
@strogonoff it looks like we are good to go, isn't it?

**Comment by strogonoff** [comment]
> @strogonoff it looks like we are good to go, isn't it?

Is there are any difference in which order those PRs are applied, #105 and #106? @CAMOBAP

**Comment by strogonoff** [comment]
Anyway, doing this one first.

**Pull request merged**
